language: node_js
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test

before_deploy:
  - npm run build

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: build
  on:
    branch: master
